// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package model

import (
	"try-work/app/model/internal"
)

// Administrator is the golang structure for table administrator.
type Administrator internal.Administrator

// 注册请求参数，用于前后端交互参数格式约定
type AdministratorApiSignUpReq struct {
	Username  string `v:"required|length:6,16#账号不能为空|账号长度应当在:min到:max之间"`
	Password  string `v:"required|length:6,16#请输入确认密码|密码长度应当在:min到:max之间"`
	Password2 string `v:"required|length:6,16|same:Password#密码不能为空|密码长度应当在:min到:max之间|两次密码输入不相等"`
	RealName  string
}

type AdministratorApiSignInReq struct {
	Username string `v:"required|length:6,16#账号不能为空|账号长度应当在:min到:max之间"`
	Password string `v:"required|length:6,16#请输入确认密码|密码长度应当在:min到:max之间"`
}

// 注册输入参数
type AdministratorServiceSignUpReq struct {
	Username    string
	Password    string
	RealName    string
	Status      int
	LastLoginIn int64
	CreatedAt   int64
	UpdatedAt   int64
}
