// ==========================================================================
// Code generated by GoFrame CLI tool. DO NOT EDIT.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/os/gtime"
)

// Administrator is the golang structure for table administrator.
type Administrator struct {
	Id          uint        `orm:"id,primary"    json:"id"`          //
	Username    string      `orm:"username"      json:"username"`    // 用户名
	Password    string      `orm:"password"      json:"password"`    // 密码
	RealName    string      `orm:"real_name"     json:"realName"`    // 真实姓名
	Status      int         `orm:"status"        json:"status"`      // 状态
	LastLoginAt *gtime.Time `orm:"last_login_at" json:"lastLoginAt"` // 上次登录时间
	CreatedAt   *gtime.Time `orm:"created_at"    json:"createdAt"`   //
	UpdatedAt   *gtime.Time `orm:"updated_at"    json:"updatedAt"`   //
}
