// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package dao

import (
	"try-work/app/dao/internal"
)

// administratorDao is the manager for logic model data accessing
// and custom defined data operations functions management. You can define
// methods on it to extend its functionality as you wish.
type administratorDao struct {
	internal.AdministratorDao
}

var (
	// Administrator is globally public accessible object for table administrator operations.
	Administrator = administratorDao{
		internal.Administrator,
	}
)

// Fill with you ideas below.
