// ==========================================================================
// This is auto-generated by gf cli tool. DO NOT EDIT THIS FILE MANUALLY.
// ==========================================================================

package internal

import (
	"github.com/gogf/gf/database/gdb"
	"github.com/gogf/gf/frame/g"
	"github.com/gogf/gf/frame/gmvc"
)

// AdministratorDao is the manager for logic model data accessing
// and custom defined data operations functions management.
type AdministratorDao struct {
	gmvc.M                       // M is the core and embedded struct that inherits all chaining operations from gdb.Model.
	DB      gdb.DB               // DB is the raw underlying database management object.
	Table   string               // Table is the table name of the DAO.
	Columns administratorColumns // Columns contains all the columns of Table that for convenient usage.
}

// AdministratorColumns defines and stores column names for table administrator.
type administratorColumns struct {
	Id          string //
	Username    string // 用户名
	Password    string // 密码
	RealName    string // 真实姓名
	Status      int    // 状态
	LastLoginAt int64  // 上次登录时间
	CreatedAt   int64  //
	UpdatedAt   int64  //
}

var (
	// Administrator is globally public accessible object for table administrator operations.
	Administrator = AdministratorDao{
		M:     g.DB("default").Model("administrator").Safe(),
		DB:    g.DB("default"),
		Table: "administrator",
		Columns: administratorColumns{
			Id:          "id",
			Username:    "username",
			Password:    "password",
			RealName:    "real_name",
			Status:      1,
			LastLoginAt: 0,
			CreatedAt:   0,
			UpdatedAt:   0,
		},
	}
)
